# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d178aca881b8954effc543147439aa019e5a434fdc15f141c7a481c986787841cab941eba73d34b2ea712daadbb2ae955e5388974f3479251bf79653a84dc967

test:
  secret_key_base: c96da52998daed621f01cd8369836ebefa48cadfa934aad06667d6f68beed060e37ff432dcce7a68c937626449ffdada0af834faa34231192c6c4165487f6bef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
